# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WeatherScraperUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(840, 511)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.browseSaveFolderButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseSaveFolderButton.setObjectName("browseSaveFolderButton")
        self.gridLayout.addWidget(self.browseSaveFolderButton, 2, 2, 1, 1)
        self.saveFolderLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.saveFolderLineEdit.setObjectName("saveFolderLineEdit")
        self.gridLayout.addWidget(self.saveFolderLineEdit, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.saveHtmlButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveHtmlButton.setObjectName("saveHtmlButton")
        self.horizontalLayout.addWidget(self.saveHtmlButton)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        self.csvFileLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.csvFileLineEdit.setObjectName("csvFileLineEdit")
        self.gridLayout.addWidget(self.csvFileLineEdit, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.browseCsvFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseCsvFileButton.setObjectName("browseCsvFileButton")
        self.gridLayout.addWidget(self.browseCsvFileButton, 1, 2, 1, 1)
        self.ballParkJsonLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ballParkJsonLineEdit.setObjectName("ballParkJsonLineEdit")
        self.gridLayout.addWidget(self.ballParkJsonLineEdit, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.browseBallParkJsonButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseBallParkJsonButton.setObjectName("browseBallParkJsonButton")
        self.gridLayout.addWidget(self.browseBallParkJsonButton, 0, 2, 1, 1)
        self.timerSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.timerSpinBox.setProperty("value", 10)
        self.timerSpinBox.setObjectName("timerSpinBox")
        self.gridLayout.addWidget(self.timerSpinBox, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.urlLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.urlLineEdit.setObjectName("urlLineEdit")
        self.horizontalLayout_2.addWidget(self.urlLineEdit)
        self.goButton = QtWidgets.QPushButton(self.centralwidget)
        self.goButton.setObjectName("goButton")
        self.horizontalLayout_2.addWidget(self.goButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 840, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Pitch File"))
        self.browseSaveFolderButton.setText(_translate("MainWindow", "..."))
        self.saveFolderLineEdit.setPlaceholderText(_translate("MainWindow", "Select the folder to save HTML files to..."))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.saveHtmlButton.setText(_translate("MainWindow", "Save HTML"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.csvFileLineEdit.setPlaceholderText(_translate("MainWindow", "Select pitch csv file..."))
        self.label_2.setText(_translate("MainWindow", "Output Folder"))
        self.browseCsvFileButton.setText(_translate("MainWindow", "..."))
        self.ballParkJsonLineEdit.setPlaceholderText(_translate("MainWindow", "Select ball park data in JSON..."))
        self.label_3.setText(_translate("MainWindow", "Ballpark Data"))
        self.browseBallParkJsonButton.setText(_translate("MainWindow", "..."))
        self.urlLineEdit.setPlaceholderText(_translate("MainWindow", "Website URL"))
        self.goButton.setText(_translate("MainWindow", "Go"))


